---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: curve-csi-nodeplugin
  namespace: csi-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: curve-csi-nodeplugin
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.curve.csi.netease.com/aggregate-to-curve-csi-nodeplugin: "true"
rules: []

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: curve-csi-nodeplugin-rules
  labels:
    rbac.curve.csi.netease.com/aggregate-to-curve-csi-nodeplugin: "true"
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "update"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "create", "list", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: curve-csi-nodeplugin
subjects:
- kind: ServiceAccount
  name: curve-csi-nodeplugin
  namespace: csi-system
roleRef:
  kind: ClusterRole
  name: curve-csi-nodeplugin
  apiGroup: rbac.authorization.k8s.io
