apiVersion: v1
kind: Pod
metadata:
  annotations:
    # https://kubernetes.io/docs/tutorials/clusters/apparmor/
    container.apparmor.security.beta.kubernetes.io/my-container: unconfined
  name: csi-curve-test-block
spec:
  containers:
  - name: my-container
    image: debian
    command:
    - sleep
    - "3600"
    securityContext:
      capabilities:
        add: ["SYS_ADMIN"]
    volumeDevices:
    - devicePath: /dev/block
      name: my-volume
  volumes:
  - name: my-volume
    persistentVolumeClaim:
      claimName: curve-test-pvc-block
